name: Android APK Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Project files fix
        run: |
          if [ ! -f main.py ] && [ -f ana.py ]; then
            cp ana.py main.py
          fi

          if [ ! -f buildozer.spec ] && [ -f Buildozer.spec ]; then
            cp Buildozer.spec buildozer.spec
          fi

          sed -i 's/^android.api *= *.*/android.api = 36/' buildozer.spec || true

          echo "Files:"
          ls -la

      - name: Build APK with official Buildozer
        run: |
          docker pull kivy/buildozer:latest

          yes | docker run -i --rm \
            -v "$PWD":/home/user/hostcwd \
            kivy/buildozer:latest \
            -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Ball-Escape-APK
          path: bin/*.apk
          if-no-files-found: error
